### ISSUE TITLE
Instruction Manual

### ISSUE THREAD

**Issue by davepallot** [opencadc/vos#44]
I am part of the SDP group from ICRAR, headed by Andreas Wicenec, and I would like to review your VOSpace 2.1 reference implementation but I am having issues running it. Is there an instruction manual or some other piece of documentation that can guide me through the steps of building, installing and operating this software?
Thank you.

**Comment by davepallot** [comment]
Hi Brain,
Thank you for the prompt reply. 
I am happy with the second option (cavern) for now as we would just like to review what you have and how that may fit in with our plans for using a VOSpace implementation in the future (which we are still working through).
The only thing I have managed to do at this point is build the codebase, so if you have any tips on how to get it configured and running that would be appreciated. 

Regards
Dave

**Comment by brianmajor** [comment]
Hi Dave,

After the build you will find a .war file in the build/libs directory of the cavern project.  You should place this war file in the webapps directory of a server that has apache tomcat installed.  When apache starts up (or detects the file when running) it will untar the file and the web service is then installed at the location http://host/cavern.

In the root folder of the cavern repository source there is a file called Cavern.properties.  This file should be placed a directory named 'config' off the home directory of the user running tomcat.  This user must be `root` due to some file system permissions that are required for some vospace operations.  We plan to modify that later.

In Cavern.properties, the key VOS_FILESYSTEM_ROOT should be set to the directory for which you'd like to set aside for vospace data/metadata.  This can be a local directory or a mounted directory.

That should get you a little way.  Let me know how that goes.  
Brian

**Comment by davepallot** [comment]
Thanks Brian. Appreciate the help. Ill let you know how I go. 
Regards
Dave
