### ISSUE TITLE
MD5 sum missing for zero length files in cavern

### ISSUE THREAD

**Issue by andamian** [opencadc/vos#99]
The optimization for empty files is to create just the node but the server does not return the corresponding md5 sum in that case (`d41d8cd98f00b204e9800998ecf8427e`). This creates problems in `vos` which relies on the checksum to be present all the time.

Patch, when available, should be tested with `vos` before release.

**Comment by pdowler** [comment]
The md5 checksum will be missing in many files in cavern (anything written via mounted fs) so vostools will have to accommodate that and fall back to file length and timestamps to decide what to do.

Since in principle VOSpace allows for "create DataNode" (no bytes) and then later writing of bytes, I would not want to set the checksum until bytes were written (so that bugs that fail to add the checksum attr leave no attr rather than a wrong one). 

0-length file is already unambiguous so I don't think this is a problem. Can I close this?
